spring:
  datasource:
    url: jdbc:mysql://10.211.55.6:3306/BLOGDB?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Abcd1996!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888